# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:  
  name: default
steps:
- script: echo hello world
- task: Windows Application Driver@0
  inputs:
    OperationType: 'Start'
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'automation.py'
- task: Windows Application Driver@0
  inputs:
    OperationType: 'Stop'